package dbutils

const train = `
	CREATE TABLE IF NOT EXISTS train(
		ID INTEGER PRIAMRY KEY ,
		DRIVER_NAME VARCHAR(64) NULL,
		OPERATING_STATUS BOOLEAN
	)
`
const station = `
	CREATE TABLE IF NOT EXISTS station(
		ID INTEGER PRIMARY KEY ,
		NAME VARCHAR(64) NULL,
		CLOSING_TIME TIME NULL
	)
`

const schedule = `
	CREATE TABLE IF NOT EXISTS schedule(
		ID INTEGER PRIMARY KEY ,
		TRAIN_ID INT,
		STATION_ID INT,
		ARRIVAL_TIME TIME,
		FOREIGN KEY (TRAIN_ID) REFERENCES train(ID),
		FOREIGN KEY (STATION_ID) REFERENCES station(ID)
	)
`
